#!/usr/bin/env bash
# =============================================================================
# sync-shared-refs.sh — Materialize skills/_shared/references/ into each skill
#
# Skills that need a shared reference declare it in get_shared_refs()
# (scripts/_skills-lib.sh). This script copies the canonical file from
# skills/_shared/references/ into <skill>/references/ as a real committed file.
#
# Real files (not symlinks) are what make the library portable: a skill folder
# copied out of this repo by the installer, `claude --plugin-dir`, or
# `npx skills add` must carry its own references with it.
#
# Usage:
#   ./scripts/sync-shared-refs.sh           # write the copies
#   ./scripts/sync-shared-refs.sh --check   # verify only, exit 1 on drift (CI)
# =============================================================================

set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_skills-lib.sh"

CHECK_MODE=0
case "${1:-}" in
  --check) CHECK_MODE=1 ;;
  "")      ;;
  *)       log_error "Unknown argument: $1"; echo "Usage: $0 [--check]" >&2; exit 2 ;;
esac

GENERATED_MARKER="Generated by scripts/sync-shared-refs.sh"
DRIFTED=0
WROTE=0

# Renders the canonical shared file with a generated-by header, so a copy is
# never mistaken for a hand-editable file.
render_shared_ref() {
  local filename="$1"
  printf '<!-- %s from skills/_shared/references/%s. Do not edit directly. -->\n\n' \
    "$GENERATED_MARKER" "$filename"
  cat "$SHARED_DIR/$filename"
}

is_generated_copy() {
  local file="$1"
  [ -f "$file" ] && head -1 "$file" | grep -q "$GENERATED_MARKER"
}

report_drift() {
  DRIFTED=1
  log_error "$1"
}

[ -d "$SHARED_DIR" ] || { log_error "Missing $SHARED_DIR"; exit 1; }

if [ "$CHECK_MODE" -eq 1 ]; then
  log_section "Checking shared references are in sync"
else
  log_section "Syncing shared references"
fi

while IFS= read -r skill_dir; do
  skill_name="$(skill_name_from_dir "$skill_dir")"
  shared_files="$(get_shared_refs "$skill_name")"
  refs_dir="$skill_dir/references"
  rel_skill="${skill_dir#"$REPO_ROOT"/}"

  # Expected copies for this skill.
  for filename in $shared_files; do
    src="$SHARED_DIR/$filename"
    dest="$refs_dir/$filename"
    rel_dest="${dest#"$REPO_ROOT"/}"

    if [ ! -f "$src" ]; then
      report_drift "$skill_name declares $filename, but skills/_shared/references/$filename does not exist"
      continue
    fi

    if [ "$CHECK_MODE" -eq 1 ]; then
      if [ -L "$dest" ]; then
        report_drift "$rel_dest is a symlink — expected a real file"
      elif [ ! -f "$dest" ]; then
        report_drift "$rel_dest is missing"
      elif ! render_shared_ref "$filename" | diff -q - "$dest" >/dev/null 2>&1; then
        report_drift "$rel_dest differs from skills/_shared/references/$filename"
      fi
    else
      mkdir -p "$refs_dir"
      rm -f "$dest"
      render_shared_ref "$filename" > "$dest"
      WROTE=$((WROTE + 1))
    fi
  done

  # Generated copies left behind after a skill stops declaring a ref.
  [ -d "$refs_dir" ] || continue
  for existing in "$refs_dir"/*.md; do
    [ -e "$existing" ] || continue
    is_generated_copy "$existing" || continue

    filename="$(basename "$existing")"
    if ! printf '%s\n' $shared_files | grep -qx "$filename"; then
      rel_existing="${existing#"$REPO_ROOT"/}"
      if [ "$CHECK_MODE" -eq 1 ]; then
        report_drift "$rel_existing is a generated copy that $skill_name no longer declares"
      else
        rm -f "$existing"
        log_info "Removed stale copy: $rel_existing"
      fi
    fi
  done
done < <(list_skill_dirs)

if [ "$DRIFTED" -ne 0 ]; then
  cat <<'EOF'

Shared references are out of sync. Run:

  ./scripts/sync-shared-refs.sh

and commit the result. Edit the canonical file in skills/_shared/references/,
never the generated copy inside a skill.
EOF
  exit 1
fi

if [ "$CHECK_MODE" -eq 1 ]; then
  log_success "Shared references are in sync"
else
  log_success "Synced $WROTE shared reference file(s)"
fi
